### PR TITLE
added ejs package ejs template and view folder

### PR DESCRIPTION
**Pull request by Stephen-Roach**
Added the ejs package, created a bare bones ejs template to make sure it works, and created the view folder. Also deleted the css folder and moved the css file to the public folder.

### CODE REVIEW

**Comment by Stephen-Roach** [comment]
[Views folder](https://trello.com/c/eQOmkft1/29-views-folder)

**Comment by Stephen-Roach** [comment]
[EJS Template build](https://trello.com/c/XCx2mOfM/21-ejs-template-build)

**Review by RpowellIV — CHANGES_REQUESTED** [review]
add the -L back to the nodemon dev

**Comment by Stephen-Roach** [comment]
Fixed the nodemon dev, forgot I tried taking the -L off when the nodemon wouldn't work! Nice catch

**Review by RpowellIV — APPROVED** [review]

**Pull request merged**
